Repository StudyConnect-ZHAW/Backend, pull requests merged in 2025-05, with the labels that each got.

#86 feat/#84 secure open api with entra
  .example.env
  StudyConnect.API/Controllers/User/UserController.cs
  StudyConnect.API/Program.cs
  StudyConnect.API/StudyConnect.API.csproj
  StudyConnect.API/appsettings.Development.json
  StudyConnect.Data/Repositories/UserRepository.cs
  compose.yaml
Labels: feat

#106 Feat/#104 add authorizaton groups
  StudyConnect.API/Controllers/Group/GroupController.cs
  StudyConnect.API/Dtos/Requests/Group/GroupCreateDto.cs
  StudyConnect.Core/Common/ErrorMessages.cs
  StudyConnect.Core/Interfaces/IGroupMemberRepository.cs
  StudyConnect.Core/Interfaces/IGroupRepository.cs
  StudyConnect.Data/ModelMapper.cs
  StudyConnect.Data/Repositories/GroupMemberRepository.cs
  StudyConnect.Data/Repositories/GroupRepository.cs
Labels: docs, feat

#112 Fix/noissue hotfix resolve unique title
  StudyConnect.API/Controllers/Forum/PostController.cs
  StudyConnect.API/Dtos/Responses/Forum/PostReadDto.cs
  StudyConnect.Data/Repositories/GroupRepository.cs
  StudyConnect.Data/Repositories/PostRepository.cs
Labels: bug
