Repository StudyConnect-ZHAW/Backend, pull requests merged in 2025-04, with the labels that each got.

#46 fix: disable qualitygate [NOISSUE]
  .github/workflows/build.yaml
Labels: ci, fix, patch

#43 Feat/#39 subtask 3 design of the user endpoint
  StudyConnect.API/Controllers/BaseController.cs
  StudyConnect.API/Controllers/User/UserController.cs
  StudyConnect.API/Controllers/WeatherForecastController.cs
  StudyConnect.API/Program.cs
  StudyConnect.API/StudyConnect.API.csproj
  StudyConnect.API/WeatherForecast.cs
Labels: feat

#47 ci/[NOISSUE] fix frontend build
  .github/workflows/ci-cd-staging.yaml
Labels: ci, fix

#45 Feat/#38 forum endpoint
  StudyConnect.API/Controllers/Forum/CommentController.cs
  StudyConnect.API/Controllers/Forum/PostController.cs
  StudyConnect.API/Controllers/GroupsController.cs
Labels: docs, feat

#49 fix/NOISSUE Docker compose
  README.md
  StudyConnect.API/Dockerfile
  StudyConnect.API/compose.yaml
  start-and-open.ps1
  start-and-open.sh
Labels: build, fix

#50 hotfix/NOISSUE fixing cicd build
  .github/workflows/ci-cd-staging.yaml
Labels: ci, fix

#48 chore/NOISSUE template adjustment
  .github/pull_request_template.md
Labels: chore

#65 build/NOISSUE frontend container fix
  .example.env
  .github/workflows/build.yaml
  .github/workflows/cleanup-sonarqube.yaml
  README.md
  StudyConnect.API/Program.cs
  StudyConnect.Data/appsettings.json
  compose.yaml
  start-and-open.ps1
  start-and-open.sh
Labels: build, fix
